version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=2004
      - DB_NAME=todo_list

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=2004
      - MYSQL_DATABASE=todo_list
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: